[project]
site_name = "Bad Weather Mount Tester"
site_url = "https://jscheidtmann.github.io/BadWeatherMountTester/"
site_author = "Jens Scheidtmann"
docs_dir = "docs/root"
site_dir = "site"

[project.theme]
features = []
